# Generated by Django 4.2.6 on 2023-10-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='unite_price',
            field=models.DecimalField(decimal_places=2, default='20', max_digits=10),
            preserve_default=False,
        ),
    ]
