# Generated by Django 4.2.6 on 2023-10-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceapp', '0002_invoicedetail_unite_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_name',
            new_name='InvoiceCustomerName',
        ),
        migrations.RenameField(
            model_name='invoicedetail',
            old_name='unite_price',
            new_name='unit_price',
        ),
    ]
